apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: MyExampleDomain
  description: Just a Dummy Domain
spec:
  owner: user:ceo-singh
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: System-A
  description: Just a System
spec:
  owner: user:lead-a-singh
  domain: user:MyExampleDomain
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: System-B
  description: Just Another System
spec:
  owner: user:lead-b-singh
  domain: MyExampleDomain
