apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: system-a-web
  description: Web App for System A
spec:
  type: website
  lifecycle: production
  owner: team-a
  system: System-A
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: system-a-backend
  description: Backend Services for System A
spec:
  type: service
  lifecycle: production
  owner: team-a
  system: System-A
  providesApis: [system-a-backend-api]
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: system-a-db
  description: Stores Data related to System A
spec:
  type: database
  owner: team-a
  system: System-A
